### ISSUE TITLE
issue in elasticsearch when i try deploy it shows  me a error

### ISSUE THREAD

**Issue by hitanshu1** [mitchtabian/ForSale#5]
![1](https://user-images.githubusercontent.com/36150455/37786735-65106012-2e23-11e8-84b9-e02bb22de7b2.jpg)
![2](https://user-images.githubusercontent.com/36150455/37786736-6578eea2-2e23-11e8-9198-919c96030beb.jpg)
![3](https://user-images.githubusercontent.com/36150455/37786737-65bcde46-2e23-11e8-86a3-43ef89a44315.jpg)
![4](https://user-images.githubusercontent.com/36150455/37786741-66cdca66-2e23-11e8-9f6e-53d1c2809f4c.jpg)

**Comment by mitchtabian** [comment]
Says it could be a problem with npm. Do you have the newest version of npm
on your PC?

**Comment by hitanshu1** [comment]
Yes I am using the new one

**Comment by hitanshu1** [comment]
Its showing it's probably not a problem with npm

**Comment by mitchtabian** [comment]
Oh, you're right. Let me take another quick look.

**Comment by hitanshu1** [comment]
Okay sure Sir ..I try to solved this from last 10 days ...please help me
out

**Comment by mitchtabian** [comment]
Take a look at this:
https://github.com/firebase/firebase-functions/issues/69

Try running this:
npm i --save firebase-admin

**Comment by mitchtabian** [comment]
And try replacing the return statement with this:

`return request(elasticSearchRequest).then(function(response) {
			 console.log("ElasticSearch response", response);
		  }).catch(function(error) {
							console.log("Error:", error);
						  });
`

**Comment by hitanshu1** [comment]
Okay sir let me check

**Comment by hitanshu1** [comment]
Still the same error showing

**Comment by hitanshu1** [comment]
![01](https://user-images.githubusercontent.com/36150455/37815656-c6343482-2e95-11e8-9eb7-1b2148e3bd87.jpg)
![02](https://user-images.githubusercontent.com/36150455/37815657-c6784546-2e95-11e8-8d9e-435de3a3ab94.jpg)
![03](https://user-images.githubusercontent.com/36150455/37815658-c6bc6898-2e95-11e8-8619-5e92c2b47fb0.jpg)
![04](https://user-images.githubusercontent.com/36150455/37815660-c7037f08-2e95-11e8-9cff-110909de6b41.jpg)
![05](https://user-images.githubusercontent.com/36150455/37815661-c743bb2c-2e95-11e8-8633-05550cd4a0d5.jpg)
![06](https://user-images.githubusercontent.com/36150455/37815662-c78ed8b4-2e95-11e8-8725-193926e48e6a.jpg)

**Comment by hitanshu1** [comment]
Sir I need your help

**Comment by hitanshu1** [comment]
thanks

**Comment by qhuang20** [comment]
@hitanshu1 how did you fix the problem?
I really need your help.
I'm still getting: Each then() should return a value or throw  promise/always-return
after trying the above solutions

**Comment by mitchtabian** [comment]
Firebase changed the data returned to the cloud function. I'll have to update it.

**Comment by hitanshu1** [comment]
Is it sloved
